### ISSUE TITLE
LineChart not rendering as expected

### ISSUE THREAD

**Issue by AntouanK** [jdarling/d3rrc#2]
@jdarling Tried to use your LineChart in a small demo I have, and I ended up having DOM elements added in the chart every time it was rendering.
I had over 1000 X and Y axis for example, and lines upon lines.
I guess you manipulate the DOM outside the React lifecycle and you end up with multiple DOM instances?

**Comment by jdarling** [comment]
This is fixed in the latest version pushed.  I had it fixed before but didn't push the changes until I completed v1.0.0 due to other fixes I wanted to get in place as well.

**Comment by AntouanK** [comment]
Nice, thanks.
I'll try to check it out later.

By the way, I've been using this lib last week, for some graphs I wanted in react ( http://jhudson8.github.io/react-chartjs/ ).
You could probably have a similar page with examples and code to showcase your graphs?
( perf numbers would be very helpful IMHO )

**Comment by jdarling** [comment]
Actually, there is an examples page: http://rawgit.com/jdarling/d3rrc/master/examples/

It's just hidden away in the long readme LOL.

React-ChartJS looks really interesting, will have to take a look.  Off hand I can tell they are better with styles than I am.

Performance numbers, I'm not sure what I would measure, any ideas?

**Comment by jdarling** [comment]
Oh, and I'm working on the documentation currently.  Going to be rough at first, but it will be there :D

**Comment by AntouanK** [comment]
Thanks for the examples, I'll have a look when I finish this project I'm working on.
It's kind of important to show them for someone who wants to try the library.

Performance wise, I guess rendering time needed as data points increase maybe? Or as they change and graph has to re-render ( or re-size etc )
And weight code wise, how much code we add in order to use those graphs.

What I would like to try, is make an SVG template for a graph, and use react to make it a component. 
No D3, no chart-js or other extra library.
I think that would be much more light-weight and fast. Obviously, needs much more work too.
